apiVersion: v1
kind: Service
metadata:
  name: bloc-infra
  labels:
    name: bloc-infra
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
    - port: 5672
      targetPort: 5672
      name: rabbit-amqp
    - port: 15672
      targetPort: 15672
      name: rabbit-ui
    - port: 9000
      targetPort: 9000
      name: minio-api
    - port: 9001
      targetPort: 9001
      name: minio-ui
  clusterIP: None
  selector:
    role: bloc-infra
---
apiVersion: v1
kind: Service
metadata:
  name: bloc-infra-read
  labels:
    name: bloc-infra-read
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
    - port: 5672
      targetPort: 5672
      name: rabbit-amqp
    - port: 15672
      targetPort: 15672
      name: rabbit-ui
    - port: 9001
      targetPort: 9001
      name: minio-ui
  selector:
    role: bloc-infra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bloc-infra
spec:
  serviceName: "bloc-infra"
  replicas: 1
  selector:
    matchLabels:
      role: bloc-infra
      environment: test
  template:
    metadata:
      labels:
        role: bloc-infra
        environment: test
    spec:
      containers:
        - name: mongo
          image: mongo:5.0.5
          args: ["--dbpath", "/data/db", "--port", "27017"]
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo
              mountPath: /data/db
        - name: rabbit
          image: rabbitmq:3.9.11-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "blocRabbit"
            - name: RABBITMQ_DEFAULT_PASS
              value: "blocRabbitPasswd"
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
          volumeMounts:
            - name: rabbit
              mountPath: /var/lib/rabbitmq/mnesia
        - name: minio
          env:
            - name: MINIO_ROOT_USER
              value: blocMinio
            - name: MINIO_ROOT_PASSWORD
              value: blocMinioPasswd
          image: minio/minio:RELEASE.2021-11-24T23-19-33Z
          resources:
            requests:
              ephemeral-storage: 2Gi
          imagePullPolicy: IfNotPresent
          args:
            - server
            - /data
            - --address 
            - :9000
            - --console-address 
            - :9001
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console-ui
          volumeMounts:
            - name: minio
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: mongo
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: rabbit
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: minio
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
