apiVersion: v1
kind: Service
metadata:
  name: bloc-server-and-ui
  labels:
    name: bloc-server-and-ui
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: server
    - port: 80
      targetPort: 80
      name: ui
  selector:
    role: bloc-server-and-ui
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bloc-server-and-ui
spec:
  serviceName: "bloc-base"
  replicas: 1
  selector:
    matchLabels:
      role: bloc-server-and-ui
      environment: test
  template:
    metadata:
      labels:
        role: bloc-server-and-ui
        environment: test
    spec:
      containers:
        - name: bloc-server
          image: billiepander/bloc_server:v8
          command:
          - "/app/main"
          args:
          - "--app_name"
          - "local"
          - "--rabbitMQ_connection_str"
          - "blocRabbit:blocRabbitPasswd@bloc-infra-read:5672"
          - "--minio_connection_str"
          - "blocMinio:blocMinioPasswd@bloc-infra-read:9000"
          - "--mongo_connection_str"
          - ":@bloc-infra-read:27017"
          ports:
            - containerPort: 8000
              name: bloc-server-api