version: '3'  
services: 
  mongo:
    image: mongo:5.0.5
    command: ["mongod", "--dbpath", "/data/db", "--port", "27017"]
    container_name: mongo_bloc
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=blocMongo
      - MONGO_INITDB_ROOT_PASSWORD=blocMongoPasswd
    restart: always
  rabbit:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbit_bloc
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=blocRabbit
      - RABBITMQ_DEFAULT_PASS=blocRabbitPasswd
    restart: always
  minio:
    image: minio/minio:RELEASE.2021-11-24T23-19-33Z
    command: ["minio", "server", "/data", "--address", ":9000", "--console-address", ":9001"]
    container_name: minio_bloc
    ports:
      - "9000:9000"
      # - "9001:9001"
    environment:
      - MINIO_ROOT_USER=blocMinio
      - MINIO_ROOT_PASSWORD=blocMinioPasswd
    restart: always
  influxDB:
    image: influxdb:2.1.1
    container_name: influx_bloc
    ports:
      - "8086:8086"
    restart: always