version: '3'  
services: 
  bloc-server:
    image: blocapp/bloc-server:0.1
    container_name: bloc_server
    ports:
      - "8080:8080"
    command: 
      - "/app/main"
      - "--app_name"
      - "local"
      - "--rabbitMQ_connection_str"
      - "blocRabbit:blocRabbitPasswd@host.docker.internal:5672"
      - "--minio_connection_str"
      - "blocMinio:blocMinioPasswd@host.docker.internal:9000"
      - "--mongo_connection_str"
      - "blocMongo:blocMongoPasswd@host.docker.internal:27017"
      - "--influxdb_connection_str"
      - "blocInflux:blocInfluxPasswd@host.docker.internal:8086/?token=sqiQ-uFzig9aGPHxBm2w-dJzDss7kbhlw-x8JYOUeExFRH3VCD3J9yS37FPtcs85brldFVFZrMB84rn0F8Yuew==&organization=bloc"
      - "--server_host"
      - "0.0.0.0"
      - "--server_port"
      - "8080"
